version: "3.4"
services:
    app:
      container_name: "phone-review-server"
      restart: "always"
      build:
        context: .
        args:
          - PORT = ${PORT}
      ports:
        - 3333:${PORT}
      env_file:
        - .env
